### ISSUE TITLE
Remove unused symbols 

### ISSUE THREAD

**Issue by mikeprecious** [sonburn/symbol-organizer#8] opened 2017-01-25 17:11 UTC
Heads-up: Checking remove unused symbols in the dialogue causes the plugin to not work. Unchecking it, the plugin and its other functions appear to work.

**Comment by sonburn** [comment] 2017-01-25 17:41
Thank you for the heads up. I have been away on business the last couple days so I have not had an opportunity to thoroughly test the plugin in Sketch 42. I will dig into this in the next couple days.

**Comment by sonburn** [comment] 2017-01-27 19:30
So I have just tested this thoroughly myself, and I can't seem to find any issues with any of the options in Symbol Organizer in Sketch 42. Remove Unused Symbols works for me; doesn't freeze the plugin and still ignores symbols which are nested or used as overrides. Are you still running into this issue? If so, I would like to work with you to figure out what's going on. We could start by confirming which version of MacOS you are running, and checking Console.app for a log entry of the failure.

**Comment by edwardbiz** [comment] 2017-01-30 09:58
I have the same issue As @mikeprecious

**Comment by sonburn** [comment] 2017-01-30 16:09
@mikeprecious or @edwardbiz, would either of you be able to share a file which has this issue? I have tested this with simple and complex documents, and I cannot seem to reproduce what you describe. I understand if you cannot, due to sensitive nature of what you might be working on.

In lieu of that, another option would be to try and catch an error in the logs when you run the plugin. Console.app is kind of useless right now, but if you open Sketch from Terminal.app (copy/paste the following and hit enter - /Applications/Sketch.app/Contents/MacOS/Sketch), then open your file and run the plugin, you should see an error appear there. If so, please copy/paste the error, or provide a screenshot. This would help immensely in solving the issue for you, and I assume others.

**Comment by edwardbiz** [comment] 2017-01-30 17:34
Hi @sonburn just got that out of the terminal. let me know if this helps 

2017-01-30 17:32:18.022 Sketch[12696:2849660] Plugin at URL file:///Users/edward.battistini/Library/Application%20Support/com.bohemiancoding.sketch3/Plugins/ArtboardTricks.sketchplugin/ and plugin at URL file:///Users/edward.battistini/Library/Application%20Support/com.bohemiancoding.sketch3/Plugins/Sketch%20Artboardtricks/ArtboardTricks.sketchplugin/ have the same bundle identifier (net.nurik.roman.sketch.artboardtricks). The second plugin will be ignored. «Plugin Developer»
2017-01-30 17:32:18.045 Sketch[12696:2849660] Plugin at URL file:///Users/edward.battistini/Library/Application%20Support/com.bohemiancoding.sketch3/Plugins/Slicer/Slicer.sketchplugin/ and plugin at URL file:///Users/edward.battistini/Library/Application%20Support/com.bohemiancoding.sketch3/Plugins/Slicer.sketchplugin/ have the same bundle identifier (co.ozzik.slicer). The second plugin will be ignored. «Plugin Developer»
Verified OK
Verified OK
Verified OK
Verified OK
Verified OK
Verified OK
Verified OK
Verified OK
Verified OK
Verified OK
Verified OK
Verified OK
Verified OK
Verified OK
Verified OK
Verified OK
Verified OK
Verified OK
Verified OK
Verified OK
Verified OK
Verified OK
Verified OK
Verified OK
Verified OK
Verified OK
Verified OK
Verified OK
Verified OK
Verified OK
Verified OK
Verified OK
Verified OK
objc[12696]: Class EDSemver is implemented in both /Users/edward.battistini/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Panels.sketchplugin/Contents/Sketch/Panels.framework/Panels (0x1062de908) and /Users/edward.battistini/Library/Application Support/com.bohemiancoding.sketch3/Plugins/AutoLayoutPlugin.sketchplugin/Contents/Resources/AutoLayoutPlugin.bundle/Contents/MacOS/AutoLayoutPlugin (0x108977810). One of the two will be used. Which one is undefined.
2017-01-30 17:32:33.243 Sketch[12696:2849660] Run commnad: import-library
2017-01-30 17:32:57.225 Sketch[12696:2849660] This application is trying to draw a very large combo box, 28 points tall.  Vertically resizable combo boxes are not supported, but it happens that 10.4 and previous drew something that looked kind of sort of okay.  The art in 10.5 does not break up in a way that supports that drawing.  This application should be revised to stop using large combo boxes.  This warning will appear once per app launch.
2017-01-30 17:33:07.281 Sketch[12696:2849660] Exception: TypeError: null is not an object (evaluating 'child.overrides().objectForKey(0).allValues')
Jan 30 17:33:07  Symbol Organizer (Sketch Plugin)[12696] <Notice>: TypeError: null is not an object (evaluating 'child.overrides().objectForKey(0).allValues')
	line: 97
	sourceURL: /Users/edward.battistini/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Symbol Organizer.sketchplugin/Contents/Sketch/script.cocoascript
	column: 58
	stack: onRun@/Users/edward.battistini/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Symbol Organizer.sketchplugin/Contents/Sketch/script.cocoascript:97:58

**Comment by sonburn** [comment] 2017-01-30 18:59
Thanks for the logs @edwardbiz, it at least helps me figure out where the offending code is... has to do with creating the list of symbols to ignore, specifically symbols with overrides. I will dig into this and see if I can get anywhere. I don't know how complex your document is, but if there was any way to figure out which specific symbol instance with overrides was causing the issue on your end, it would be helpful if you could at least share that symbol instance in an independent sketch file, but again, I am understanding of privacy and time.

**Comment by sonburn** [comment] 2017-01-30 21:25
@mikeprecious and @edwardbiz, I just checked in an update that might solve the issue for you guys. Please grab the latest and let me know.

**Comment by edwardbiz** [comment] 2017-01-31 09:17
## Worked for me ! awesome ! no problem for me anymore... so far... Will let you know if anything else shows up ! ##

**Comment by mikeprecious** [comment] 2017-01-31 10:49
Hey guys, sorry for the radio silence - busy start to the week. Update worked for me, too. Thanks!

**Comment by sonburn** [comment] 2017-01-31 13:38
Awesome guys, thanks for verifying, and for using Symbol Organizer! I will go ahead and close the issue.

**Closed** 2017-01-31 13:38 UTC
