### ISSUE TITLE
Duplicate Group Titles

### ISSUE THREAD

**Issue by jgaylor** [sonburn/symbol-organizer#53] opened 2017-09-07 21:30 UTC
First, I LOVE this plugin. I don't know how I survived before. Also, I apologize if this was already posted, i didn't see it, and I'm happy to be pointed to it if so.

I'm getting duplicate group titles and I can't figure out why.
For example, I have two symbols named:
icons/advice-off
Icons/share

But they are showing up in different groups; both called "icons".

![screen shot 2017-09-07 at 4 29 29 pm](https://user-images.githubusercontent.com/15039182/30186109-c8b734bc-93e9-11e7-999c-55e1ae798ece.png)

**Comment by stdk00** [comment] 2017-09-07 21:38
you are using "i" and "I". thats probably why there are in two different groups :)

**Comment by jgaylor** [comment] 2017-09-07 21:43
Sorry that was a typo. I'm using lowercase in both and it's still happening. In the screenshot you can see the issue.

**Comment by jgaylor** [comment] 2017-09-07 21:50
I can reproduce the issue every time with these 3 symbols. See screenshot. If the yellow oval is named with a letter that comes after "s" in "subgroup" it will appear in a duplicate group. Hope this helps.

![screen shot 2017-09-07 at 4 48 42 pm](https://user-images.githubusercontent.com/15039182/30186788-986fb9c0-93ec-11e7-964c-c848086cb9a9.png)

**Comment by sonburn** [comment] 2017-09-23 16:39
@jgaylor Is it possible there was a leading/trailing space in the name one of those duplicates? I just in fact published an update (12.5) to resolve another enhancement request, which would resolve this issue if it was due to a leading/trailing space. If that was not the issue, could you please provide a test file where you are able to create/reproduce the issue (like the one for the screenshot above)?

**Comment by jgaylor** [comment] 2017-09-23 18:36
I've confirmed it's not because of leading/trailing space. Here's the file with some notes inside to clarify.

[jasons-test.sketch.zip](https://github.com/sonburn/symbol-organizer/files/1326745/jasons-test.sketch.zip)

**Comment by sonburn** [comment] 2017-09-24 03:26
Thanks for the example file, definitely more clear now. Please check out version 12.7 which I just published; while defining groups, each symbol will check if a group of the same name exists already, and if one does, uses it instead of creating a new one. I debated making the layer list match the adjusted order, but I think it's less confusing to leave the layer list alphabetical. Please let me know if this resolves the issue for you.

**Comment by jgaylor** [comment] 2017-09-24 16:19
Yeah! Thank you. Resolved. Works perfectly now. Great plugin. Not sure how I survived without it.

**Comment by sonburn** [comment] 2017-09-24 21:52
Fantastic, thanks again for the feedback. Will close the issue.

**Closed by sonburn** 2017-09-24 21:52 UTC
Labels: bug
