### ISSUE TITLE
Plugin removes all symbols

### ISSUE THREAD

**Issue by marcinukleja** [sonburn/symbol-organizer#47] opened 2017-08-16 06:38 UTC
Since last major Sketch update (I believe it is 46) plugin does not work anymore. Once executed it removes all symbols.

**Comment by stdk00** [comment] 2017-08-16 08:15
I can confirm that. in sketch 46.1  it removes many symbols that are being used. clearly, the plugin is not working good as it should.

**Comment by sonburn** [comment] 2017-08-16 12:55
@marcinukleja, @stdk00, What version of Symbol Organizer do you guys have?

**Comment by marcinukleja** [comment] 2017-08-16 14:52
@sonburn It was 9.0. Just updated and it works perfectly. Thanks a lot and sorry for any confusion. Don't need to mention that your plugin is awesome :).

**Comment by stdk00** [comment] 2017-08-16 15:17
@sonburn I'm using sketch 46.1 and 46.2, plugin 12.2 and it doesn't work well. I've tried deleting the plugin and reinstalling and still doesn't work. some nested symbols to which I applied an override get deleted if I select "remove unused symbols". the symbols get organized but the plugin deletes A LOT of symbols that are being used and leaves the symbols instance with the red diagonals lines which mean they lost their nested symbol.

**Comment by sonburn** [comment] 2017-08-16 15:27
@stdk00 thank you for responding. So the plugin works in general, like organization and other features, it's just the removal piece specifically that is removing _too_ much.

That is odd though... because Symbol Organizer is now using the Sketch native isSafeToDelete method for removing symbols. That means if you went to your Symbol page, selected a symbol to delete, tapped the Delete key and it **didn't** give you the prompt "Are you sure you want to delete this symbol", then it was safe to delete.

Can you confirm that a symbol my plugin is removing, is indeed giving you the prompt on the Symbols page (meaning it's not safe to delete)?

**Comment by stdk00** [comment] 2017-08-16 16:02
@sonburn I've tried manually deleting a symbol and sketch doesn't give me any warning messages although the symbols are in use. that's lame. so it should be a sketch bug that your plugin just follows. :(

**Comment by sonburn** [comment] 2017-08-16 16:09
@stdk00 in a way I am happy to know it's not the plugin that's the problem, but I am not happy the bug exists for you (and can be perceived as an issue with the plugin). Remove Unused Symbols is definitely risky, always has been, and I debated even adding it to begin with. A lot of people asked for it though, so that's why it's there. It's also why I force you to manually enable it every time you want to run it.

I am going to go ahead and close this issue for now, and I will monitor the landscape to see if others (or myself) run into the same issue. Thank you for using Symbol Organizer!

**Closed by sonburn** 2017-08-16 16:09 UTC

**Comment by sonburn** [comment] 2017-08-17 15:21
@stdk00 For what it's worth, it seems there is a bug in Sketch's isSafeToDelete, as I just ran into this issue myself. It seems **nested** symbols with overrides aren't being detected. I will submit a bug to Bohemian Coding, and explore baking some detection for these instances back into the plugin.

**Comment by stdk00** [comment] 2017-08-17 15:36
@sonburn thanks for letting me now. I was pretty sure something was wrong. can you please keep me posted if you have any update on this? thank you very much.

**Comment by sonburn** [comment] 2017-08-17 15:53
The bug report I submitted, with an example file to reproduce...

**Summary:**
MSSymbol isSafeToDelete is not detecting symbol overrides within nested nested symbols

**Steps to Reproduce:**
Create a symbol (like a list item, call it "Symbol B") which contains a nested symbol (like an icon placeholder, call it "Symbol A"). Place Symbol B in a new symbol (like a list item group, call it "Symbol C"). In Symbol C, override a Symbol A instance with another symbol (like an actual icon, call it "Symbol D").

Navigate to Symbols page, select Symbol D (which is only used as an override of a nested nested symbol), and tap Delete.

**Expected Results**
Sketch prompt indicating symbol is in use, and confirming deletion.

**Actual Results:**
Symbol is deleted, displaying the red lines in the override indicating the symbol is missing.

**Notes:**
In this linked example (https://www.dropbox.com/s/6shtevht11f375z/isSafeToDelete%20Bug.sketch?dl=0), navigate to the Symbols page and delete the Icon/Favorite symbol. Note the lack of prompt, and the red lines on the artboard on Page 1.

**Comment by sonburn** [comment] 2017-08-17 20:06
In the meantime, I just published an update that added back my symbol override protections. Can you give it a shot and let me know if you have better results?

**Comment by stdk00** [comment] 2017-08-18 12:52
@sonburn new version is working good. Thank you for the fast update. if something else comes up I'll let you know. Thanks for an awesome plugin!
