### ISSUE TITLE
Running Organizer has no effect in Sketch version 52

### ISSUE THREAD

**Issue by iconmaster** [sonburn/symbol-organizer#92] opened 2018-10-02 21:49 UTC
The Configure modal opens, but the Run command has no effect (nor does it trigger any error message).

STR:

- Navigate to a Symbols page containing more than one symbol and no non-symbol artboards
- Select "Run Symbol Organizer"

Expected result:

- Symbols are laid out according to the configuration settings

Actual result:

- No effect

**Comment by jausto** [comment] 2018-10-02 21:51
Worked in beta too

**Comment by sonburn** [comment] 2018-10-02 22:30
@iconmaster, @jausto, seems there was a last minute change in the beta that broke any plugin that uses MSSharedStyle.alloc().initWithName_firstInstance(). I've got a fix for this, but there are other changes that I don't have a fix for yet. I will publish an update as soon as I can. In the meantime, you should still be able to use Symbol Organizer, just without titles.

**Comment by iconmaster** [comment] 2018-10-02 22:38
I can confirm that unchecking "Display group titles" allows Symbol Organizer to function in Sketch v52. Thanks @sonburn!

**Comment by sonburn** [comment] 2018-10-03 14:07
I am going to close this as a duplicate of https://github.com/sonburn/symbol-organizer/issues/91 which was logged first. Fix coming imminently.

**Closed by sonburn** 2018-10-03 14:07 UTC
Labels: bug
