### ISSUE TITLE
Even after the update for Sketch 50.1, I still get the error message of 'cannot run on a page with symbols & art-boards"

### ISSUE THREAD

**Issue by dacre8iv1** [sonburn/symbol-organizer#72] opened 2018-05-15 16:43 UTC
Even after the update for Sketch 50.1, I still get the error message of 'cannot run on a page with symbols & art-boards"

**Comment by sonburn** [comment] 2018-05-17 22:35
@dacre8iv1 I am going to close this issue in fact, as it's a duplicate of this one (https://github.com/sonburn/symbol-organizer/issues/18)

**Closed by sonburn** 2018-05-17 22:35 UTC

**Comment by dacre8iv1** [comment] 2018-06-19 15:26
Thanks for your response! That would be great to explore as an enhancements since I export my symbols on artboards to my developers through Zeplin.
