### ISSUE TITLE
Sketch 72 vs Symbol organizer

### ISSUE THREAD

**Issue by domotisas** [sonburn/symbol-organizer#148] opened 2021-05-07 15:13 UTC
Hello Jason Burns,
your fabulous Plugin "Symbol Organizer" does not seem to work with Sketch version 72. It's really sad because it was precious for us :)
Thank for your great plugin.

**Comment by seanwalsh** [comment] 2021-05-07 17:44
This is a duplicate of #147

**Closed** 2021-05-10 16:33 UTC
