### ISSUE TITLE
Numeric sort isn't intelligent. Sorts to "100, 25, 50, 75"

### ISSUE THREAD

**Issue by aaronmw** [sonburn/symbol-organizer#59] opened 2017-10-10 20:08 UTC
I've got symbols for, say, "Avatars", named after their sizes: "25, 50, 75, 100", but the organizer puts them in order as 100, 25, 50, 75, which is pretty irksome for someone who's gone and installed a plugin to organize their symbols 😝

**Comment by sonburn** [comment] 2017-10-11 20:59
@aaronmw Thanks for bringing this to my attention, should be resolved in v14.0 which was just published - https://github.com/sonburn/symbol-organizer/releases/tag/14.0.

**Comment by sonburn** [comment] 2018-02-13 22:23
Closing the issue as the issue is resolved.

**Closed by sonburn** 2018-02-13 22:23 UTC
Labels: bug
