### ISSUE TITLE
Sketch v52 has broken Symbol-organizer 

### ISSUE THREAD

**Issue by srouse** [sonburn/symbol-organizer#97] opened 2018-10-03 14:27 UTC
I just updated to v52 and executed your plugin...nothing happened on a page that wasn't organized to begin with and a page that was organized also didn't change/move anything and also removed the labels that were auto generated by symbol-organzier. This plugin is wonderful and has become an important part of my process, thanks!

**Comment by sonburn** [comment] 2018-10-03 14:29
An update to Symbol Organizer was released mere moments ago. Please make sure you have version 15.3 installed.

**Comment by sonburn** [comment] 2018-10-03 14:34
Closing ticket as it's resolved and a duplicate of - https://github.com/sonburn/symbol-organizer/issues/91

**Closed by sonburn** 2018-10-03 14:34 UTC
